# Generated by Django 5.1.3 on 2024-11-12 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id_unidade', models.AutoField(primary_key=True, serialize=False)),
                ('unidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Numeradores',
            fields=[
                ('id_numerador', models.AutoField(primary_key=True, serialize=False)),
                ('contagem', models.IntegerField(default=0)),
                ('is_activate', models.BooleanField(default=False)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contador', to='numerador.modelos')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contador', to='numerador.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('auth_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='numerador.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('numeraçao', models.IntegerField(default=0)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='numerador.modelos')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='numerador.unidades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='numerador.usuarios')),
            ],
        ),
    ]
