# Generated by Django 5.1.3 on 2024-11-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='registros',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='numeradores',
            name='modelo',
        ),
        migrations.AddField(
            model_name='numeradores',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='numerador.categorias'),
        ),
        migrations.AddField(
            model_name='registros',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='numerador.categorias'),
        ),
        migrations.CreateModel(
            name='Tipocrimes',
            fields=[
                ('id_crime', models.AutoField(primary_key=True, serialize=False)),
                ('crime', models.CharField(max_length=255)),
                ('categoria_crime', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='numerador.categorias')),
            ],
        ),
        migrations.AddField(
            model_name='registros',
            name='tipo_crime',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='numerador.tipocrimes'),
        ),
        migrations.DeleteModel(
            name='Modelos',
        ),
    ]
