# Generated by Django 5.1.3 on 2024-11-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0002_categorias_remove_registros_modelo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocrimes',
            old_name='categoria_crime',
            new_name='categoria_crime_id',
        ),
    ]
