# Generated by Django 5.1.3 on 2024-11-13 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0003_rename_categoria_crime_tipocrimes_categoria_crime_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocrimes',
            old_name='categoria_crime_id',
            new_name='categoria_crime',
        ),
    ]
