# Generated by Django 5.1.6 on 2025-02-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0005_alter_registros_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeradores',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
