# Generated by Django 5.1.6 on 2025-02-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0007_alter_numeradores_contagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeradores',
            name='is_activate',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
