# Generated by Django 5.1.6 on 2025-02-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0008_alter_numeradores_is_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numeradores',
            name='contagem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='numeradores',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
