# Generated by Django 5.1.2 on 2024-10-29 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoModelo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id_unidade', models.AutoField(primary_key=True, serialize=False)),
                ('unidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Numeradores',
            fields=[
                ('id_numerador', models.AutoField(primary_key=True, serialize=False)),
                ('contagem', models.IntegerField(default=0)),
                ('modelo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contador', to='numerador.tipomodelo')),
                ('unidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contador', to='numerador.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='numerador.unidades')),
            ],
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='numerador.tipomodelo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='numerador.unidades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='numerador.usuarios')),
            ],
        ),
    ]
