# Generated by Django 5.1.2 on 2024-10-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipomodelo',
            name='ocorrencias',
            field=models.IntegerField(default=0),
        ),
    ]
