# Generated by Django 5.1.2 on 2024-10-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0002_tipomodelo_ocorrencias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registros',
            old_name='ano',
            new_name='data',
        ),
    ]
