# Generated by Django 5.1.2 on 2024-10-29 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0002_registros_numeraçao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numeradores',
            old_name='modelo_id',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='numeradores',
            old_name='unidade_id',
            new_name='unidade',
        ),
    ]
