# Generated by Django 5.1.2 on 2024-10-29 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0004_remove_tipomodelo_ocorrencias_numerador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Numerador',
            new_name='Numeradores',
        ),
    ]
