# Generated by Django 5.1.2 on 2024-11-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numerador', '0003_rename_modelo_id_numeradores_modelo_and_more'),
        ('numerador', '0005_rename_numerador_numeradores'),
    ]

    operations = [
    ]
